version: '3.3'
networks:
  transmission:
    driver: bridge

services:
  transmission:
    build:
      context: dockerTransmission
    image: ${DOCKERHUB_USER}/transmission_arm:${TRANSMISSION_TAG}
    networks:
      transmission:
        aliases:
          - transmission
    ports:
      - 51413:51413 
      - 51413:51413/udp
      - 9091:9091
    volumes:
      - /usr/share/media:/usr/share/media:rw
      - /etc/transmission/torrents:/etc/transmission/torrents:rw
      - /etc/transmission/resume:/etc/transmission/resume:rw
      - /etc/transmission/blocklists:/etc/transmission/blocklists:rw
    depends_on:
      - rutracker-proxy

  rutracker-proxy:
    build:
      context: dockerRtoProxy
    image: ${DOCKERHUB_USER}/rutracker-proxy_arm:${RUTRACKER_PROXY_TAG}
    hostname: rutracker-proxy
    ports:
      - 8080:8080
    networks:
      transmission:
        aliases:
          - rutracker-proxy

  minidlna:
    build:
      args:
        - MINIDLNA_VERSION=${MINIDLNA_VERSION}
      context: dockerMinidlna
    image: ${DOCKERHUB_USER}/minidlna_arm:${MINIDLNA_TAG}
    hostname: minidlna-home
    network_mode: "host"
    ports:
      - 1900:1900/udp
      - 8200:8200
    dns_search:
      - home
    volumes:
      - /usr/share/media:/data:ro
    restart: on-failure

